---
sudo: false
language: ruby
cache: bundler
script:
  - "bundle exec rake validate"
  - "bundle exec rake spec"
  - "bundle exec danger"
before_install:
  - rm Gemfile.lock || true
  - gem update --system
  - gem update bundler
  - gem --version
  - bundle -v
matrix:
  fast_finish: true
  include:
  - rvm: 2.4.1
    env: PUPPET_GEM_VERSION="~> 4"
  - rvm: 2.4.4
    env: PUPPET_GEM_VERSION="~> 5"
  - rvm: 2.5.1
    env: PUPPET_GEM_VERSION="~> 6"

notifications:
  email: false
